### ISSUE TITLE
emc-pypi wrapper + EMC version validity

### ISSUE THREAD

**Issue by gregrutkowski13** [Ramprasad-Group/Polymer-Molecular-Dynamics#66]
Hi, 

I saw that there were some updates to emc-pypi due to the version validity of EMC expiring on Aug 1, 2022.

I tried a fresh pmd/emc-pypi install etc but I think the wrapper is still calling the 2021 version of EMC. Is there a workaround to refresh the EMC version?

Error: main:
       Validity has run out; please download a fresh version.
       Program aborted.

Thanks -

**Comment by lichman0405** [comment]
Does it work for you if you update emc version other than v1.0.0?
Not work here for me.

**Comment by gregrutkowski13** [comment]
A newer version does not work for me either. I got around this by setting my system clock to before the expiration date of emc and running the code.

**Comment by kevinshen56714** [comment]
Please update `pmd` to v1.5.0, where the `emc-pypi` version has been bumped to the latest.
