### ISSUE TITLE
emc version issue

### ISSUE THREAD

**Issue by lichman0405** [Ramprasad-Group/Polymer-Molecular-Dynamics#78]
Hi there!
When I tried to run the sample of your code of Tg calculation, I had a problem of emc version issue.

EMC Setup v4.1 (August 1, 2021), (c) 2004-2021 Pieter J. in 't Veld

Info: reading script from "./system.esh"
Info: phase1 = {poly}
Info: project = system
Info: ntotal = 5056
Info: direction = x
Info: shape = 1
Info: force field type = "opls"
Info: force field name = "opls/2012/opls-aa"
Info: force field location = "~/miniconda3/lib/python3.8/site-packages/pyemc/emc/field"
Info: build for LAMMPS script in "../build"
Info: creating EMC build script "build.emc"
Info: assuming mol fractions
Info: creating LAMMPS run script "system.in"
Info: adding pressure sampling

Error: main:
       Validity has run out; please download a fresh version.
       Program aborted.

I emailed emc teams and they reply me that I had to update emc version to the fresh one.
Contrary, the pmd required emc-pypi version is 1.0.

Do you have any solution of it?

**Comment by gncs** [comment]
I am facing the same issue. @kevinshen56714, could you upgrade the version of `emc-pypi`, please?

**Comment by kevinshen56714** [comment]
Please update `pmd` to v1.5.0, where the `emc-pypi` version has been bumped to the latest.
